language: python
sudo: required
env:
  matrix:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: osx
      language: generic
      env: TOXENV=py27

install:
  - pip install -r ./requirements.txt 
  - python manage.py migrate


script:
  - django-lint
  - python manage.py test
  - python manage.py createsuperuser --noinput --username testadmin --email test@user.com
  - python manage.py sendtestemail --admin
