language: python
sudo: required
env:
  matrix:
  - os: linux
    dist: trusty
    sudo: required
    python: 2.7
  - os: osx
    language: generic
    env: TOXENV=py27
notifications:
  slack:
    secure: FhRol/k5l1uSypcQwFzaxhhzmt5CefqFURQaruIh1gzaOb5J7wuRfbhNw1I76A0NtmWsTTZKsQNEtDuXAg6hNGF+qMPzqs0MXKm9q4s9HuHlBbL87cmXRe3riYuajVk77MC3i5Q2F+XAAPHycOCQs1fEhu6nG2VSQKGTpVIO0s56AjzR4Of6FEqHJr0kcpe9X69/1YFDMHit5q6+47gS9k89coY38C54p21tCRQz9ZTXdVsLsBWIrovg8OtjvQytT2+fxae88m5U6X3hiXkvOMx++LU4jS/GRqLz1bzMBExT6CNuagv1GbfswIAu4Zcmas3zUkkAGbKjOnBDQ7Lm761i4ZMUxbRQmUhD7n6LbEGsKbrrWoRILT7q/B5Mo8/N0YIxwD5Ri6WXoZlI3KrOE8pdQch/TjiYlpMNkfGjI5+QPBGbmx2IMBihXO/7xLBeNswCYuSh2Lks1HX22/zw5L2D7M+IuiqXP04R+KNMHtS5qw9+YCHhGDikIzdSjMqpAVvSk65iUB2xK9WsYhOS64p/SoGHZSwKdxhUf608bkomJNoANmORHu4M6OkLS8pp4Wl3EXh3K+mI56SIYnxtic/9AaNkwMzigI6VoTaQ7qzOfQqq42AGtFP1L6uKYf5O92q6skWT28ZTYVelwtl3YMdx1RIqbPnJSzt04IX3FfY=
install:
- pip install -r ./requirements.txt
- python manage.py migrate
script:
- python manage.py test
- python manage.py createsuperuser --noinput --username testadmin --email test@user.com
- python manage.py sendtestemail --admin
