language: python
sudo: required
env:
  matrix:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: osx
      language: generic
      env: TOXENV=py27

install:
  - pip install -r ./requirements.txt 
  - python2 manage.py migrate
  - python2 manage.py runserver 2>&1

script:
  - python manage.py test
  - curl http://localhost:8000/
