language: python
#dist: centos
env:
  matrix:
    - OS_TYPE=centos OS_VERSION=6
    - OS_TYPE=centos OS_VERSION=7
    - OS_TYPE=debian OS_VERSION=9
    - OS_TYPE=debian OS_VERSION=8
    - OS_TYPE=debian OS_VERSION=7
cache: packages
before_install:
  - pip install -r ./requirements.txt 

install:
  - python2 manage.py migrate

script:
  - python manage.py test
