language: python
sudo: required
env:
  matrix:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      language: generic
      env: TOXENV=py27

install:
  - pip install -r ./requirements.txt 
  - python2 manage.py migrate

script:
  - python manage.py test
