# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_auto_20180115_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 26, 51, 581438)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='date_modified',
            field=domains.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 26, 51, 581474)),
        ),
        migrations.AlterField(
            model_name='forwarddomain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 26, 51, 582167)),
        ),
        migrations.AlterField(
            model_name='forwarddomain',
            name='date_modified',
            field=domains.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 26, 51, 582200)),
        ),
    ]
