# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20180115_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 994714)),
        ),
        migrations.AlterField(
            model_name='domain',
            name='date_modified',
            field=domains.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 994751)),
        ),
        migrations.AlterField(
            model_name='forwarddomain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 995410)),
        ),
        migrations.AlterField(
            model_name='forwarddomain',
            name='date_modified',
            field=domains.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 995442)),
        ),
    ]
