# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('quota', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='to_mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailboxes.Mailbox'),
        ),
    ]
