# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import mailboxes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0004_auto_20180115_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 997917)),
        ),
        migrations.AlterField(
            model_name='alias',
            name='date_modified',
            field=mailboxes.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 997952)),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 997158)),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='date_modified',
            field=mailboxes.models.AutoDateTimeField(default=datetime.datetime(2018, 1, 15, 2, 33, 58, 997189)),
        ),
    ]
